### ISSUE TITLE
MELPA inclusion / gptai

### ISSUE THREAD

**Issue by rommeswi** [emacs-openai/openai#11]
I think it would be great if this could at some point be published in MELPA.

Also, on MELPA, there is [gptai](https://github.com/antonhibl/gptai) and it might make sense to jointly develop the emacs implementation. I haven't looked into the details yet to compare the openai and the gptai package. I am considering writing a spacemacs layer for one of the two.

**Comment by jcs090218** [comment]
I do have plan to publish this to MELPA! However, it might take me a while to get to it since I have other packages in queued, see this thread for details https://github.com/melpa/melpa/pull/8393.

Right now, there are so many ChatGPT related packages. See [suggest a gpt plugin for me](https://www.reddit.com/r/emacs/comments/125kqax/suggest_a_gpt_plugin_for_me/) on reddit.

Other packages that uses this library are: (I've implemented them all by myself)

- https://github.com/emacs-openai/codegpt
- https://github.com/emacs-openai/chatgpt
- https://github.com/emacs-openai/dall-e

What this org offers is only the basic implementation of OpenAI's products (ChatGPT, DALL-E, etc).

**Comment by rommeswi** [comment]
Thank you for the explanation, since this is already underway then, I will close this issue.
